services:
  - type: web
    name: quiz-app
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false